import re
import json
from collections import Counter, defaultdict
from urllib.parse import urlparse, urljoin, urldefrag

from bs4 import BeautifulSoup


ALLOWED_DOMAINS = {
    "ics.uci.edu",
    "cs.uci.edu",
    "informatics.uci.edu",
    "stat.uci.edu",
}


STOP_WORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from",
    "has", "he", "in", "is", "it", "its", "of", "on", "that", "the",
    "to", "was", "were", "will", "with", "or", "not", "this", "but",
    "you", "your", "we", "our", "they", "their", "can", "all", "if",
    "more", "about", "which", "when", "who", "what", "where", "how",
    "also", "have", "had", "been", "being", "do", "does", "did", "so",
    "up", "out", "no", "him", "her", "she", "me", "my", "would", "could",
    "should", "may", "might", "shall", "into", "than", "then", "there",
    "these", "those", "am", "i", "s", "t", "re", "ll", "ve", "d",
    "us", "uc", "pdf", "theme", "favorite"
}


visited_urls = set()
word_counter = Counter()
subdomain_counter = defaultdict(int)
longest_page_url = ""
longest_page_word_count = 0


def scraper(url, resp):
    links = extract_next_links(url, resp)
    if len(visited_urls) % 50 == 0:
        save_report_data()
    return [link for link in links if is_valid(link)]


def extract_next_links(url, resp):
    # Implementation required.
    # url: the URL that was used to get the page
    # resp.url: the actual url of the page
    # resp.status: the status code returned by the server. 200 is OK, you got the page. Other numbers mean that there was some kind of problem.
    # resp.error: when status is not 200, you can check the error here, if needed.
    # resp.raw_response: this is where the page actually is. More specifically, the raw_response has two parts:
    #         resp.raw_response.url: the url, again
    #         resp.raw_response.content: the content of the page!
    # Return a list with the hyperlinks (as strings) scrapped from resp.raw_response.content

    if resp is None or resp.status != 200:
        return list()

    if resp.raw_response is None or resp.raw_response.content is None:
        return list()

    # Skip very large pages — likely binary or autogenerated
    if len(resp.raw_response.content) > 5_000_000:
        return list()

    clean_current_url, _ = urldefrag(url)

    # Parse once with lxml (faster), reuse soup for both analytics and links
    soup = BeautifulSoup(resp.raw_response.content, "lxml")

    if clean_current_url not in visited_urls:
        visited_urls.add(clean_current_url)
        print(f"[{len(visited_urls)}] Crawled: {clean_current_url}")
        update_report_data(clean_current_url, soup)

    links = list()

    for tag in soup.find_all("a", href=True):
        href = tag["href"].strip()

        if href == "":
            continue

        absolute_url = urljoin(url, href)
        clean_url, _ = urldefrag(absolute_url)

        links.append(clean_url)

    return links


def is_valid(url):
    # Decide whether to crawl this url or not.
    # If you decide to crawl it, return True; otherwise return False.
    # There are already some conditions that return False.
    try:
        parsed = urlparse(url)

        if parsed.scheme not in set(["http", "https"]):
            return False

        domain = parsed.netloc.lower()
        path = parsed.path.lower()
        query = parsed.query.lower()

        if not any(domain == allowed or domain.endswith("." + allowed)
                   for allowed in ALLOWED_DOMAINS):
            return False

        # URL length cap
        # Very long URLs are almost always traps (infinite pagination,
        # deeply nested auto-generated paths, etc.)
        if len(url) > 300:
            return False

        # Too many query parameters
        # Legitimate pages rarely need more than 5 query params.
        # More than that usually signals a dynamic trap.
        if query.count("&") > 5:
            return False

        # Repeated path segments
        # e.g. /a/b/a/b/a — a sign of an infinite directory loop
        if has_repeated_path_segments(path):
            return False

        # Calendar / events traps
        # Many academic sites expose infinite calendar views; block the
        # common URL patterns that generate them.
        # Date-stamped event archive pages (e.g. /events/2024-03)
        if re.search(r"/events/\d{4}-\d{2}", path):
            return False

        # Explicit date filter params
        if re.search(r"[?&](date|year|month|day)=", query):
            return False

        # iCal export endpoints (e.g. tribe_events ical feeds)
        if "ical" in path or "ical" in query:
            return False

        # The Events Calendar (tribe) plugin generates infinite date pages
        if "tribe" in path or "tribe" in query:
            return False

        # DokuWiki traps
        # DokuWiki generates near-infinite pages through its action/ns params.
        if "doku.php" in path:
            return False

        # DokuWiki media fetch/detail handlers
        if "lib/exe/fetch.php" in path or "lib/exe/detail.php" in path:
            return False

        # Pasted media blobs inside DokuWiki
        if "pasted%3a" in path or "pasted:" in path:
            return False

        # DokuWiki namespace param drives infinite crawl
        if re.search(r"[?&]ns=", query):
            return False

        # DokuWiki revision/diff/edit/login action pages
        if re.search(r"[?&](rev=|do=diff|do=revisions|do=edit|do=login)", query):
            return False

        # Known problematic domains / paths

        # Eppstein's image gallery: thousands of photo pages, no text value
        if domain == "ics.uci.edu" and path.startswith("/~eppstein/pix"):
            return False

        # Fano combinatorics rules pages: combinatorial explosion of URLs
        if domain == "fano.ics.uci.edu" and path.startswith("/ca/rules"):
            return False

        # GitLab: login walls, infinite repo diffs, blob/raw file trees
        if domain == "gitlab.ics.uci.edu":
            return False

        # GRAPE: generates huge numbers of low-value auto-pages
        if domain == "grape.ics.uci.edu":
            return False

        # ISG events section is a calendar trap
        if domain == "isg.ics.uci.edu" and path.startswith("/events"):
            return False

        # WICS events section is also a calendar trap
        if domain == "wics.ics.uci.edu" and path.startswith("/events"):
            return False

        # NGS: WordPress blog with infinite paginated author/category/blog pages
        if domain == "ngs.ics.uci.edu":
            return False

        # Block path-based pagination e.g. /page/228 which slips through query param checks
        if re.search(r"/page/\d+", path):
            return False

        # Swiki/MoinMoin wikis generate infinite edit/history/search pages
        if "swiki" in domain:
            return False

        # Wayback-machine-style archive paths: duplicate historical snapshots
        # Pattern: /YYYYMMDDHHMMSS/ (14-digit timestamp)
        if re.search(r"/\d{14}/", path):
            return False

        # Generic query-param traps

        # Session identifiers: every user gets a unique URL → infinite URL space
        if re.search(r"[?&](sid|sessionid|phpsessid|jsessionid)=", query):
            return False

        # UTM tracking params: same page content, infinite URL variants
        if "utm_" in query:
            return False

        # Sorting/filtering params create near-duplicate pages with same content
        if re.search(r"[?&](sort|order|filter|orderby)=", query):
            return False

        # Deep pagination: allow first ~10 pages, block the long tail
        # Covers ?page=, ?p=, ?start=, ?offset=, ?from=, ?begin=
        page_match = re.search(r"[?&](?:page|p|start|offset|from|begin)=(\d+)", query)
        if page_match and int(page_match.group(1)) > 10:
            return False

        # WordPress comment reply links expand infinitely
        if re.search(r"[?&]replytocom=", query):
            return False

        # WordPress admin/login/REST API endpoints
        if "/wp-login" in path or "/wp-admin" in path or "/wp-json" in path:
            return False

        # Image extensions (belt-and-suspenders before the big regex)
        image_extensions = (".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".ico")
        if any(path.endswith(ext) for ext in image_extensions):
            return False

        # Generic file extension blacklist
        return not re.match(
            r".*\.(css|js|bmp|gif|jpe?g|ico"
            + r"|png|tiff?|mid|mp2|mp3|mp4"
            + r"|wav|avi|mov|mpeg|ram|m4v|mkv|ogg|ogv|pdf"
            + r"|ps|eps|tex|ppt|pptx|doc|docx|xls|xlsx|names"
            + r"|data|dat|exe|bz2|tar|msi|bin|7z|psd|dmg|iso"
            + r"|epub|dll|cnf|tgz|sha1"
            + r"|thmx|mso|arff|rtf|jar|csv"
            + r"|rm|smil|wmv|swf|wma|zip|rar|gz)$",
            path
        )

    except TypeError:
        print("TypeError for", url)
        return False


def update_report_data(url, soup):
    global longest_page_url
    global longest_page_word_count

    # Decompose non-visible tags so get_text() returns only human-readable content
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()

    text = soup.get_text(separator=" ")

    # All alphabetic tokens — used for longest-page count (assignment definition)
    words = re.findall(r"[a-zA-Z]+", text.lower())

    # Filtered tokens — used only for the word frequency table
    useful_words = [w for w in words if w not in STOP_WORDS and len(w) > 1]

    word_counter.update(useful_words)

    # Longest page is measured by ALL words, not stop-word-filtered words
    if len(words) > longest_page_word_count:
        longest_page_word_count = len(words)
        longest_page_url = url

    subdomain = urlparse(url).netloc.lower()
    subdomain_counter[subdomain] += 1


def save_report_data():
    print(f"[SAVE] {len(visited_urls)} unique pages | longest: {longest_page_url} ({longest_page_word_count} words)")
    data = {
        "unique_pages": len(visited_urls),
        "longest_page": {
            "url": longest_page_url,
            "word_count": longest_page_word_count
        },
        "top_50_words": word_counter.most_common(50),
        "subdomains": dict(sorted(subdomain_counter.items()))
    }

    with open("crawl_report_data.json", "w", encoding="utf-8") as file:
        json.dump(data, file, indent=4)


def has_repeated_path_segments(path):
    parts = [part for part in path.lower().split("/") if part]
    counts = Counter(parts)

    for count in counts.values():
        if count >= 3:
            return True

    return False

